name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release notes
        id: notes
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
