name: ci
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
jobs:
  python:
    runs-on: ubuntu-latest
    env:
      FASTAPI_BEARER_TOKEN: realizati
      BASE_URL: http://127.0.0.1:8000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install black ruff pyright pytest requests
      - name: Start API server
        run: |
          nohup uvicorn main:app --host 127.0.0.1 --port 8000 --log-level error &
          for i in `seq 1 30`; do
            sleep 0.3
            if curl -fsS -H "Authorization: Bearer ${FASTAPI_BEARER_TOKEN}" http://127.0.0.1:8000/healthz >/dev/null; then
              echo "API is up"; break; fi;
          done
      - name: Ruff
        run: ruff check .
      - name: Black (check only)
        run: black --check .
      - name: Pyright
        run: pyright
      - name: Pytest (smoke)
        run: pytest -q
