name: CI

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black pyright pytest

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Type check (pyright)
        run: pyright

      - name: Start app
        env:
          FASTAPI_BEARER_TOKEN: realizati
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 & echo $! > uvicorn.pid
          sleep 2
          curl -sSf http://localhost:8000/healthz || (echo 'healthz failed'; cat uvicorn.pid; kill $(cat uvicorn.pid); exit 1)

      - name: Smoke tests
        env:
          BASE_URL: http://localhost:8000
          BEARER_TOKEN: realizati
        run: pytest -q tests/test_smoke_api.py

      - name: Stop app
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then kill $(cat uvicorn.pid) || true; fi
